import { fetchJson, ensureHttpUrl } from "@/lib/http";
import type { HostingApp, ProviderResult } from "@/lib/types";
const BASE = "https://api.discloud.app/v2";
type DiscloudApp = { id?: string; appID?: string; name?: string; online?: boolean; status?: string; ram?: number; ramMB?: number; cpu?: string | number; lang?: string; type?: string | number; exitCode?: number; subdomain?: string; domain?: string; url?: string; container?: { cpu?: string | number; ram?: string | number; status?: string } };
function token(){ const value=process.env.DISCLOUD_API_TOKEN?.trim(); if(!value) throw new Error("DISCLOUD_API_TOKEN não configurado"); return value; }
function headers(){ return { "api-token": token() }; }
function unwrapApps(raw:any):DiscloudApp[]{ if(Array.isArray(raw)) return raw; if(Array.isArray(raw?.apps)) return raw.apps; if(Array.isArray(raw?.data)) return raw.data; if(raw?.app&&typeof raw.app==="object") return [raw.app]; if(raw?.apps&&typeof raw.apps==="object") return Object.values(raw.apps); return []; }
function stateOf(app:DiscloudApp):HostingApp["status"]{ const raw=String(app.container?.status||app.status||"").toLowerCase(); if(app.online===true||/online|running|ready|started/.test(raw)) return "online"; if(app.online===false||/offline|stopped|dead/.test(raw)) return "offline"; if(/build|starting|deploy|restart/.test(raw)) return "building"; if(/error|failed|crash/.test(raw)||(typeof app.exitCode==="number"&&app.exitCode!==0)) return "error"; return "unknown"; }
function normalize(app:DiscloudApp):HostingApp|null{ const id=String(app.id||app.appID||"").trim(); if(!id) return null; return { id,provider:"discloud",name:app.name||`Discloud ${id}`,status:stateOf(app),url:ensureHttpUrl(app.url||app.domain||(app.subdomain?`${app.subdomain}.discloud.app`:undefined)),cpu:app.cpu!=null?String(app.cpu):app.container?.cpu!=null?String(app.container.cpu):undefined,ram:app.ram!=null?`${app.ram} MB`:app.ramMB!=null?`${app.ramMB} MB`:app.container?.ram!=null?String(app.container.ram):undefined,language:app.lang||(typeof app.type==="string"?app.type:undefined),latestDeploymentState:stateOf(app),description:"Aplicação hospedada na Discloud",metadata:{workspace:true,upload:true},actions:["start","stop","restart"] }; }
export async function listDiscloudApps():Promise<ProviderResult>{ if(!process.env.DISCLOUD_API_TOKEN) return {provider:"discloud",configured:false,apps:[]}; try{ const raw=await fetchJson<any>(`${BASE}/app/all`,{headers:headers()},15000); return {provider:"discloud",configured:true,apps:unwrapApps(raw).map(normalize).filter(Boolean) as HostingApp[]}; }catch(error){ return {provider:"discloud",configured:true,apps:[],error:error instanceof Error?error.message:"Falha na Discloud"}; } }
export async function getDiscloudAppDetails(id:string):Promise<Partial<HostingApp>>{ const [a,b]=await Promise.allSettled([fetchJson<any>(`${BASE}/app/${encodeURIComponent(id)}`,{headers:headers()},12000),fetchJson<any>(`${BASE}/app/${encodeURIComponent(id)}/status`,{headers:headers()},12000)]); const candidates:DiscloudApp[]=[]; if(a.status==="fulfilled") candidates.push(...unwrapApps(a.value)); if(b.status==="fulfilled") candidates.push(...unwrapApps(b.value)); const view=normalize({ ...Object.assign({},...candidates), id }); if(!view) return {status:"unknown"}; return {status:view.status,url:view.url,cpu:view.cpu,ram:view.ram,language:view.language,latestDeploymentState:view.latestDeploymentState,metadata:view.metadata,actions:view.actions}; }
export async function getDiscloudLogs(id:string){ const raw=await fetchJson<any>(`${BASE}/app/${encodeURIComponent(id)}/logs`,{headers:headers()},15000); const value=raw?.logs??raw?.log??raw?.data?.logs??raw?.data??raw?.message??raw; if(typeof value==="string") return value; if(Array.isArray(value)) return value.map((item)=>typeof item==="string"?item:JSON.stringify(item)).join("\n"); return JSON.stringify(value,null,2); }
export async function discloudAction(id:string,action:"start"|"stop"|"restart"){ return fetchJson<any>(`${BASE}/app/${encodeURIComponent(id)}/${action}`,{method:"PUT",headers:headers()},15000); }
