import { NextRequest, NextResponse } from "next/server";
import type { Provider } from "@/lib/types";
export const dynamic="force-dynamic"; export const runtime="nodejs";
const DISCLOUD_BASE="https://api.discloud.app/v2"; const MAX_TEXT_BYTES=5*1024*1024; const MAX_UPLOAD_BYTES=200*1024*1024;
function isWorkspaceProvider(value:string):value is Provider{return value==="discloud"||value==="nextcloud";} function cleanPath(value:string|null|undefined){return String(value||"").replace(/\\/g,"/").replace(/^\/+|\/+$/g,"").replace(/\/+/g,"/");}
function discloudHeaders(){const token=process.env.DISCLOUD_API_TOKEN?.trim();if(!token) throw new Error("DISCLOUD_API_TOKEN não configurado");return {"api-token":token};}
async function responseJson(response:Response){const text=await response.text();let data:any=text;try{data=text?JSON.parse(text):{};}catch{}if(!response.ok) throw new Error(`${response.status} ${typeof data==="string"?data:JSON.stringify(data)}`);return data;}
function findArray(value:any):any[]{if(Array.isArray(value))return value;if(!value||typeof value!=="object")return[];for(const key of ["files","items","entries","explorer","data","result"])if(Array.isArray(value[key]))return value[key];return[];}
function normalizeDiscloudEntries(raw:any,cwd:string){return findArray(raw).map((item:any)=>{if(typeof item==="string")return{name:item.split("/").pop()||item,path:cleanPath(item),type:"file"};const name=String(item.name||item.fileName||item.basename||String(item.path||"").split("/").pop()||"");const path=cleanPath(item.path||item.cPath||(cwd?`${cwd}/${name}`:name));const rawType=String(item.type||item.typeFile||item.kind||"").toLowerCase();const type=item.isDirectory||item.directory||/dir|folder|directory/.test(rawType)?"directory":"file";return{name,path,type,size:Number(item.size||item.bytes||0)||undefined,modified:item.modified||item.updatedAt||item.mtime||undefined};}).filter((entry:any)=>entry.name);}
function discloudContent(raw:any){const found=[raw?.fileContent,raw?.content,raw?.data?.fileContent,raw?.data?.content,raw?.result?.fileContent,raw?.result?.content].find((value)=>typeof value==="string");if(typeof found==="string")return found;if(typeof raw==="string")return raw;return JSON.stringify(raw,null,2);}
function nextcloudConfig(){const serverUrl=process.env.NEXTCLOUD_URL?.trim().replace(/\/+$/,"");const username=process.env.NEXTCLOUD_USERNAME?.trim();const password=process.env.NEXTCLOUD_APP_PASSWORD?.trim();const rootPath=cleanPath(process.env.NEXTCLOUD_ROOT_PATH);if(!serverUrl||!username||!password)throw new Error("Nextcloud não configurado");return{serverUrl,username,password,rootPath};}
function basic(username:string,password:string){return `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`;} function encodePath(value:string){return cleanPath(value).split("/").filter(Boolean).map(encodeURIComponent).join("/");}
function nextcloudUrl(relative=""){const{serverUrl,username,rootPath}=nextcloudConfig();const full=[rootPath,cleanPath(relative)].filter(Boolean).join("/");return`${serverUrl}/remote.php/dav/files/${encodeURIComponent(username)}${full?`/${encodePath(full)}`:""}`;}
function xmlText(block:string,tag:string){const match=block.match(new RegExp(`<(?:[^:>]+:)?${tag}[^>]*>([\\s\\S]*?)<\\/(?:[^:>]+:)?${tag}>`,"i"));return match?.[1]?.replace(/<[^>]+>/g,"").trim()||"";} function decodeXml(value:string){return value.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
function parseNextcloudEntries(xml:string,cwd:string){const blocks=xml.match(/<(?:[^:>]+:)?response\b[\s\S]*?<\/(?:[^:>]+:)?response>/gi)||[];const requested=cleanPath(cwd);const entries:any[]=[];for(const block of blocks){const hrefRaw=xmlText(block,"href");if(!hrefRaw)continue;let href="";try{href=decodeURIComponent(decodeXml(hrefRaw));}catch{href=decodeXml(hrefRaw);}let pathName=href;try{if(/^https?:\/\//i.test(href))pathName=new URL(href).pathname;}catch{}const trimmed=pathName.replace(/\/+$/,"");const name=trimmed.split("/").pop()||"";if(!name)continue;const isDir=/<(?:[^:>]+:)?collection\b/i.test(block);const rootPath=new URL(nextcloudUrl(requested)).pathname.replace(/\/+$/,"");if(trimmed===rootPath)continue;entries.push({name,path:cleanPath([requested,name].filter(Boolean).join("/")),type:isDir?"directory":"file",size:Number(xmlText(block,"getcontentlength"))||undefined,modified:xmlText(block,"getlastmodified")||undefined});}return entries.sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name):a.type==="directory"?-1:1);}
async function listDiscloud(id:string,path:string){const url=new URL(`${DISCLOUD_BASE}/app/${encodeURIComponent(id)}/explorer`);if(path)url.searchParams.set("cPath",path);const data=await responseJson(await fetch(url,{headers:discloudHeaders(),cache:"no-store"}));return{cwd:path,entries:normalizeDiscloudEntries(data,path),capabilities:{read:true,write:true,upload:false,deployZip:true}};}
async function openDiscloud(id:string,path:string){const url=new URL(`${DISCLOUD_BASE}/app/${encodeURIComponent(id)}/explorer/open`);url.searchParams.set("cPath",path);return{path,content:discloudContent(await responseJson(await fetch(url,{headers:discloudHeaders(),cache:"no-store"})))};}
async function saveDiscloud(id:string,path:string,content:string){return responseJson(await fetch(`${DISCLOUD_BASE}/app/${encodeURIComponent(id)}/explorer/edit`,{method:"PUT",headers:{...discloudHeaders(),"Content-Type":"application/json"},body:JSON.stringify({cPath:path,fileContent:content})}));}
async function listNextcloud(path:string){const{username,password}=nextcloudConfig();const response=await fetch(nextcloudUrl(path),{method:"PROPFIND",headers:{Authorization:basic(username,password),Depth:"1","Content-Type":"application/xml"},body:'<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:resourcetype/><d:getcontentlength/><d:getlastmodified/></d:prop></d:propfind>',cache:"no-store"});const xml=await response.text();if(!response.ok&&response.status!==207)throw new Error(`Nextcloud WebDAV HTTP ${response.status}: ${xml.slice(0,500)}`);return{cwd:path,entries:parseNextcloudEntries(xml,path),capabilities:{read:true,write:true,upload:true,deployZip:false}};}
async function openNextcloud(path:string){const{username,password}=nextcloudConfig();const response=await fetch(nextcloudUrl(path),{headers:{Authorization:basic(username,password)},cache:"no-store"});if(!response.ok)throw new Error(`Nextcloud HTTP ${response.status}`);const length=Number(response.headers.get("content-length")||0);if(length>MAX_TEXT_BYTES)throw new Error("Arquivo grande demais para abrir no editor (máximo 5 MB).");const contentType=response.headers.get("content-type")||"";if(contentType&&!/^text\//i.test(contentType)&&!/json|javascript|xml|yaml|toml|svg/i.test(contentType))throw new Error("Este arquivo parece binário e não pode ser editado como texto.");return{path,content:await response.text()};}
async function saveNextcloud(path:string,content:string){const{username,password}=nextcloudConfig();const response=await fetch(nextcloudUrl(path),{method:"PUT",headers:{Authorization:basic(username,password),"Content-Type":"text/plain; charset=utf-8","X-NC-WebDAV-AutoMkcol":"1"},body:content});if(!response.ok)throw new Error(`Nextcloud HTTP ${response.status}`);return{ok:true};}
export async function GET(request:NextRequest,context:{params:Promise<{provider:string;id:string}>}){try{const{provider,id}=await context.params;if(!isWorkspaceProvider(provider))return NextResponse.json({error:"Workspace não suportado por este provedor."},{status:400});const action=request.nextUrl.searchParams.get("action")||"list";const path=cleanPath(request.nextUrl.searchParams.get("path"));if(action==="list")return NextResponse.json(provider==="discloud"?await listDiscloud(id,path):await listNextcloud(path));if(action==="open")return NextResponse.json(provider==="discloud"?await openDiscloud(id,path):await openNextcloud(path));return NextResponse.json({error:"Ação inválida."},{status:400});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Falha no workspace."},{status:500});}}
export async function PUT(request:NextRequest,context:{params:Promise<{provider:string;id:string}>}){try{const{provider,id}=await context.params;if(!isWorkspaceProvider(provider))return NextResponse.json({error:"Workspace não suportado."},{status:400});const body=await request.json();const path=cleanPath(body?.path);const content=typeof body?.content==="string"?body.content:"";if(!path)return NextResponse.json({error:"Caminho ausente."},{status:400});await(provider==="discloud"?saveDiscloud(id,path,content):saveNextcloud(path,content));return NextResponse.json({ok:true,path});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Falha ao salvar arquivo."},{status:500});}}
export async function POST(request:NextRequest,context:{params:Promise<{provider:string;id:string}>}){try{const{provider,id}=await context.params;if(!isWorkspaceProvider(provider))return NextResponse.json({error:"Upload não suportado."},{status:400});const form=await request.formData();const file=form.get("file");const action=String(form.get("action")||"upload");const cwd=cleanPath(String(form.get("path")||""));if(!(file instanceof File))return NextResponse.json({error:"Arquivo ausente."},{status:400});if(!file.size||file.size>MAX_UPLOAD_BYTES)return NextResponse.json({error:"Arquivo deve ter no máximo 200 MB."},{status:413});if(provider==="discloud"){if(action!=="deploy")return NextResponse.json({error:"Na Discloud, o upload direto é feito como deploy/commit de um ZIP."},{status:400});if(!file.name.toLowerCase().endsWith(".zip"))return NextResponse.json({error:"A Discloud exige arquivo .ZIP para commit."},{status:415});const upstream=new FormData();upstream.set("file",new File([await file.arrayBuffer()],file.name,{type:file.type||"application/zip"}));const result=await responseJson(await fetch(`${DISCLOUD_BASE}/app/${encodeURIComponent(id)}/commit`,{method:"PUT",headers:discloudHeaders(),body:upstream}));return NextResponse.json({ok:true,result});}const target=cleanPath([cwd,file.name].filter(Boolean).join("/"));const{username,password}=nextcloudConfig();const response=await fetch(nextcloudUrl(target),{method:"PUT",headers:{Authorization:basic(username,password),"Content-Type":file.type||"application/octet-stream","X-NC-WebDAV-AutoMkcol":"1"},body:new Uint8Array(await file.arrayBuffer())});if(!response.ok)throw new Error(`Nextcloud HTTP ${response.status}`);return NextResponse.json({ok:true,path:target});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Falha no upload."},{status:500});}}
